"""
generate_yolo_labels.py -- Create YOLO-seg label files from the fibre dataset
=============================================================================
Reads manifest.json, decodes per-instance RGB masks, extracts polygon contours,
and writes YOLO segmentation .txt labels under yolo_format/labels/{split}/.

Also copies images into yolo_format/images/{split}/ (val and test images
currently sit in train/images/ -- the manifest split field is the authority)
and writes a dataset.yaml ready for ultralytics training / validation.

Output layout:
    fibre_dataset/yolo_format/
        images/
            train/  val/  test/
        labels/
            train/  val/  test/
        dataset.yaml

Usage:
    python generate_yolo_labels.py
    python generate_yolo_labels.py --data_dir ./fibre_dataset
    python generate_yolo_labels.py --epsilon_factor 0.003 --dry_run
"""

import argparse
import json
import os
import shutil

import cv2
import numpy as np
from PIL import Image


CLASS_ID = 0  # single class: fibre


def mask_to_polygon(binary_mask, epsilon_factor=0.002):
    """
    Convert a binary mask to a simplified YOLO-seg polygon.

    Returns a flat list [x1, y1, x2, y2, ...] normalised to [0, 1],
    or None if no valid contour is found.
    """
    H, W = binary_mask.shape
    contours, _ = cv2.findContours(
        binary_mask.astype(np.uint8),
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE,
    )
    if not contours:
        return None

    contour = max(contours, key=cv2.contourArea)
    if cv2.contourArea(contour) < 1:
        return None

    epsilon = epsilon_factor * cv2.arcLength(contour, closed=True)
    approx  = cv2.approxPolyDP(contour, max(epsilon, 1.0), closed=True)

    if len(approx) < 3:
        return None

    pts = approx.reshape(-1, 2).astype(float)
    pts[:, 0] /= W
    pts[:, 1] /= H
    np.clip(pts, 0.0, 1.0, out=pts)

    return pts.flatten().tolist()


def generate_labels(data_dir, epsilon_factor, dry_run=False):
    manifest_path = os.path.join(data_dir, "manifest.json")
    with open(manifest_path) as f:
        manifest = json.load(f)

    yolo_root = os.path.join(data_dir, "yolo_format")

    stats = {"images_copied": 0, "labels_written": 0, "instances": 0, "skipped": 0}

    for sample in manifest["samples"]:
        split    = sample["split"]
        img_src  = os.path.join(data_dir, sample["image"])
        mask_src = os.path.join(data_dir, sample["mask"])
        stem     = os.path.splitext(os.path.basename(sample["image"]))[0]

        img_dst_dir   = os.path.join(yolo_root, "images", split)
        label_dst_dir = os.path.join(yolo_root, "labels", split)

        if not dry_run:
            os.makedirs(img_dst_dir,   exist_ok=True)
            os.makedirs(label_dst_dir, exist_ok=True)

        # -- Copy image to the correct split subfolder --
        img_dst = os.path.join(img_dst_dir, os.path.basename(img_src))
        if not os.path.exists(img_dst):
            if not dry_run:
                shutil.copy2(img_src, img_dst)
            stats["images_copied"] += 1

        # -- Decode instance masks --
        mask_rgb = np.array(Image.open(mask_src).convert("RGB"), dtype=np.uint8)
        H, W = mask_rgb.shape[:2]

        lines = []
        for fibre in sample["fibres"]:
            rgb       = np.array(fibre["mask_rgb"], dtype=np.uint8)
            inst_mask = np.all(mask_rgb == rgb, axis=-1).astype(np.uint8)

            if inst_mask.sum() < 16:
                stats["skipped"] += 1
                continue

            polygon = mask_to_polygon(inst_mask, epsilon_factor)
            if polygon is None or len(polygon) < 6:
                stats["skipped"] += 1
                continue

            coords = " ".join(f"{v:.6f}" for v in polygon)
            lines.append(f"{CLASS_ID} {coords}")
            stats["instances"] += 1

        # -- Write label file --
        if not dry_run:
            label_path = os.path.join(label_dst_dir, f"{stem}.txt")
            with open(label_path, "w") as f:
                f.write("\n".join(lines))
        stats["labels_written"] += 1

    return stats


def write_yaml(data_dir):
    yolo_root = os.path.join(data_dir, "yolo_format")
    abs_root  = os.path.abspath(yolo_root).replace("\\", "/")
    yaml_path = os.path.join(yolo_root, "dataset.yaml")

    content = (
        f"# Auto-generated by generate_yolo_labels.py\n"
        f"path: {abs_root}\n"
        f"train: images/train\n"
        f"val:   images/val\n"
        f"test:  images/test\n"
        f"\n"
        f"nc: 1\n"
        f"names:\n"
        f"  0: fibre\n"
    )
    with open(yaml_path, "w") as f:
        f.write(content)
    print(f"  dataset.yaml  -> {yaml_path}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Generate YOLO-seg labels from the fibre dataset",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--data_dir",       default="./fibre_dataset",
                   help="Path to fibre_dataset root (contains manifest.json)")
    p.add_argument("--epsilon_factor", type=float, default=0.002,
                   help="Polygon simplification: fraction of contour perimeter "
                        "(smaller = more points; default 0.002)")
    p.add_argument("--dry_run",        action="store_true",
                   help="Report what would be written without writing anything")
    return p.parse_args()


def main():
    args = parse_args()

    print("Generating YOLO segmentation labels")
    print(f"  data_dir       : {args.data_dir}")
    print(f"  epsilon_factor : {args.epsilon_factor}")
    if args.dry_run:
        print("  DRY RUN -- nothing will be written\n")

    stats = generate_labels(args.data_dir, args.epsilon_factor, args.dry_run)

    if not args.dry_run:
        write_yaml(args.data_dir)

    print(f"\n  Images copied  : {stats['images_copied']}")
    print(f"  Label files    : {stats['labels_written']}")
    print(f"  Instances      : {stats['instances']}")
    print(f"  Skipped        : {stats['skipped']}")
    print("\nDone.")


if __name__ == "__main__":
    main()